src/WebApps/WebHookHandler/Models/ErrorViewModel.cs
using System;

namespace WebHookHandler.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/WebApps/WebHookHandler/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebHookHandler.Models;

namespace WebHookHandler.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/WebApps/WebHookHandler/Controllers/WebHooksController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.Extensions.Logging;

namespace WebHookHandler.Controllers
{
    public class WebHookModel
    {
        public int nodeId { get; set; }
        public int versionId { get; set; }
        public string version { get; set; }
        public string previousVersion { get; set; }
        public DateTime versionModificationDate { get; set; }
        public int modifiedBy { get; set; }
        public string path { get; set; }
        public string name { get; set; }
        public string displayName { get; set; }
        public string eventName { get; set; }
        public int subscriptionId { get; set; }
        public DateTime sentTime { get; set; }
        public DateTime arrivedTime { get; set; }
        public string[] changedFields { get; set; }

        public override string ToString()
        {
            return JsonSerializer.Serialize(this, new JsonSerializerOptions()
            {
                WriteIndented = true
            });
        }
    }

    public class WebHooksController : Controller
    {
        private readonly ILogger<WebHooksController> _logger;
        private static readonly object Sync = new();
        public static List<WebHookModel> WebHooks { get; } = new();

        public WebHooksController(ILogger<WebHooksController> logger)
        {
            _logger = logger;
        }

        [HttpGet()]
        [ActionName("test")]
        public IActionResult TestGet([FromQuery] WebHookModel model)
        {
            SaveModel(model);

            return new OkResult();
        }
        [HttpPost]
        [ActionName("test")]
        public IActionResult Test([FromBody] WebHookModel model)
        {
            SaveModel(model);

            return new OkResult();
        }
        [HttpPatch]
        [ActionName("test")]
        public IActionResult TestPatch([FromBody] WebHookModel model)
        {
            SaveModel(model);

            return new OkResult();
        }
        [HttpPut]
        [ActionName("test")]
        public IActionResult TestPut([FromBody] WebHookModel model)
        {
            SaveModel(model);

            return new OkResult();
        }
        [HttpDelete]
        [ActionName("test")]
        public IActionResult TestDel([FromBody] WebHookModel model)
        {
            SaveModel(model);

            return new OkResult();
        }

        [HttpGet]
        public IActionResult Clear()
        {
            WebHooks.Clear();
            return Redirect("/");
        }

        private void SaveModel(WebHookModel model)
        {
            model.arrivedTime = DateTime.UtcNow;

            lock (Sync)
            {
                WebHooks.Add(model);
            }

            _logger.LogInformation("WebHook received: {model}", model);
        }
    }
}

src/WebApps/WebHookHandler/Views/Home/Index.cshtml
@using WebHookHandler.Controllers
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">WebHook handler service</h1>
    <p>List of arrived webhook requests.</p>
    @if (WebHooksController.WebHooks.Any())
    {
        <p><a asp-controller="WebHooks" asp-action="Clear">Clear list</a></p>
    }
    <p>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        Content id
                    </th>
                    <th>
                        Path
                    </th>
                    <th>
                        Event name
                    </th>
                    <th>
                        Subscription id
                    </th>
                    <th>
                        Sent at
                    </th>
                    <th>
                        Arrived at
                    </th>
                    <th>
                        Event data
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach (var webhook in WebHooksController.WebHooks
                .Where(wh => wh.arrivedTime > DateTime.UtcNow.AddDays(-1))
                .OrderByDescending(wh => wh.arrivedTime)
                .Take(100))
            {
                <tr class="@(webhook.arrivedTime > DateTime.UtcNow.AddSeconds(-30) ? "new-event" : string.Empty)">
                    <td>
                        @webhook.nodeId
                    </td>
                    <td>
                        @webhook.path
                    </td>
                    <td>
                        <strong>@webhook.eventName</strong>
                    </td>
                    <td>
                        @webhook.subscriptionId
                    </td>
                    <td>
                        @webhook.sentTime
                    </td>
                    <td>
                        @webhook.arrivedTime
                    </td>
                    <td>
                        @webhook.ToString()
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </p>
</div>

src/WebApps/WebHookHandler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebHookHandler</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebHookHandler</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebHookHandler - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>